export const staticProfileSummary: Record<string, string> = {
  '76561198422563870': `
    The user is an avid gamer with a level 12 Steam account, demonstrating consistent activity and engagement within the gaming community. Their extensive library of 462 games showcases their diverse taste in gameplay styles, ranging from Action to Simulation titles.
Their most frequently played games include Borderless Gaming, Don't Starve Together, Paladins, Don't Starve, and Tabletop Simulator. These choices suggest a preference for multiplayer and strategy-based games that offer both competitive and cooperative gameplay experiences.
The user has accumulated a total playtime of 2975 hours on Steam, indicating a significant commitment to gaming and a passion for immersive, engaging experiences. Their recent gameplay history includes titles such as The Flame in the Flood, Borderless Gaming, Wallpaper Engine, Return of the Obra Dinn, Sable, Call of the Sea, Verne: The Shape of Fantasy, Kathy Rain 2: Soothsayer, Who's Lila?, and Naiad. This collection of games showcases a continued interest in adventure, indie, and simulation titles that offer unique narratives and gameplay mechanics.
Overall, the user appears to be an enthusiastic gamer with a diverse taste in gaming genres and a preference for multiplayer and strategy-based experiences. Their extensive playtime and recent gameplay history suggest a dedication to exploring new games and immersing themselves in various worlds and stories
    `,
  '76561198199623266': `
  The user is a level 19 Steam account holder with an extensive gaming history, boasting a library of 546 games. Their preferences lean towards Action, RPG, Adventure, Indie, and Free To Play genres, showcasing a diverse taste in gameplay styles. The most frequently played games include The Binding of Isaac: Rebirth, Counter-Strike 2, Terraria, The Elder Scrolls V: Skyrim, and Plague Inc: Evolved.
The user's playtime on Steam totals an impressive 7301 hours, demonstrating a substantial commitment to gaming. Their recent gameplay history includes The Binding of Isaac: Rebirth, indicating a continued interest in challenging and engaging RPG-style games that require strategic thinking and skill. With such a vast library and significant playtime, this user is likely an avid gamer who enjoys pushing themselves to master complex titles across multiple genres.
Additionally, the user's top tags suggest they are drawn to games with unique mechanics, immersive storylines, and replayability value. Their preference for free-to-play games may indicate a budget-conscious approach to gaming or an interest in trying out new titles without commitment. Overall, this user is a dedicated gamer who values both the challenge and enjoyment that comes from exploring various game genres.
    `,
};
