import { GameInfoSchemaType } from '#api/db/models/GameInfo';
import { ExtendedGameInfo } from '#api/types/gameInfo.types';

export const getGameParamsDB = (game: ExtendedGameInfo): GameInfoSchemaType => ({
  createdAt: new Date(),
  updatedAt: new Date(),
  steam_appid: game.steam_appid,
  name: game.name,
  platforms: game.platforms || {},
  short_description: game.short_description,
  detailed_description: game.detailed_description,
  is_free: game.is_free || false,
  controller_support: game.controller_support,
  about_the_game: game.about_the_game,
  supported_languages: game.supported_languages,
  pc_requirements: game.pc_requirements || {},
  mac_requirements: game.mac_requirements || {},
  linux_requirements: game.linux_requirements || {},
  developers: game.developers || [],
  publishers: game.publishers || [],
  metacritic: game.metacritic || {},
  release_date: { date: game.release_date?.date ? new Date(game.release_date.date) : null, coming_soon: !!game.release_date?.coming_soon },
  app_url: game.app_url || `https://store.steampowered.com/app/${game.steam_appid}`,
  price_overview: game.price_overview || {},
  categories: (game.categories || []) as GameInfoSchemaType['categories'],
  genres: (game.genres || []) as GameInfoSchemaType['genres'],
  screenshots: (game.screenshots || []) as GameInfoSchemaType['screenshots'],
  movies: (game.movies?.map(movie => ({
    id: movie.id,
    name: movie.name,
    thumbnail: movie.thumbnail,
    webm: movie.webm || { '480': '', max: '' },
    mp4: movie.mp4 || { '480': '', max: '' },
  })) || []) as GameInfoSchemaType['movies'],
});

export const getGameParams = (game: GameInfoSchemaType): ExtendedGameInfo => ({
  steam_appid: game.steam_appid,
  required_age: game.required_age,
  name: game.name,
  platforms: game.platforms || {},
  short_description: game.short_description,
  detailed_description: game.detailed_description,
  is_free: game.is_free || false,
  controller_support: game.controller_support,
  about_the_game: game.about_the_game,
  supported_languages: game.supported_languages,
  pc_requirements: game.pc_requirements || {},
  mac_requirements: game.mac_requirements || {},
  linux_requirements: game.linux_requirements || {},
  developers: game.developers || [],
  publishers: game.publishers || [],
  metacritic: game.metacritic || {},
  release_date: { date: game.release_date?.date ? new Date(game.release_date.date).toLocaleDateString('fr-FR') : null, coming_soon: !!game.release_date?.coming_soon },
  app_url: game.app_url || `https://store.steampowered.com/app/${game.steam_appid}`,
  price_overview: game.price_overview || {},
  categories: (game.categories || []) as GameInfoSchemaType['categories'],
  genres: (game.genres || []) as GameInfoSchemaType['genres'],
  screenshots: (game.screenshots || []) as GameInfoSchemaType['screenshots'],
  movies: (game.movies?.map(movie => ({
    id: movie.id,
    name: movie.name,
    thumbnail: movie.thumbnail,
    webm: movie.webm || { '480': '', max: '' },
    mp4: movie.mp4 || { '480': '', max: '' },
  })) || []) as GameInfoSchemaType['movies'],
});